services:
  - type: web
    runtime: node
    name: frathouse-picasso
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start -- -p $PORT -H 0.0.0.0
    envVars:
      - key: NODE_ENV
        value: production
